# Generated by Django 4.2.1 on 2024-04-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='AccessLevel',
            field=models.CharField(blank=True, choices=[('admin', 'مدیر'), ('user', 'کاربر'), ('ins', 'بازرس')], max_length=10, null=True, verbose_name='سطح دسترسی'),
        ),
        migrations.CreateModel(
            name='WhUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whUserId', models.ForeignKey(db_column='whUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WhUserTokens',
            },
        ),
    ]
