# Generated by Django 4.2.1 on 2024-04-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_accesslevel_whusertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whusertoken',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='whusertoken',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
