# Generated by Django 4.2.1 on 2024-05-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_whusertoken_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lname',
        ),
    ]
