# Generated by Django 4.2.1 on 2024-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(blank=True, max_length=50, null=True, verbose_name='زیرسیستم')),
                ('attribute', models.CharField(blank=True, max_length=50, null=True, verbose_name='ویژگی')),
                ('value', models.TextField(blank=True, null=True, verbose_name='مقدار')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'db_table': 'tblSettings',
            },
        ),
    ]
