# Generated by Django 4.2.1 on 2024-04-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestText', models.CharField(max_length=1000)),
                ('cellphone', models.CharField(max_length=15)),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=3, verbose_name=(('UUID', 'UUID'), ('RND', 'RndEsalat')))),
                ('Code_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode.barcode')),
            ],
        ),
    ]
