# Generated by Django 4.2.1 on 2024-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nationalid', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='کدملی شرکت')),
                ('companyfaname', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام شرکت')),
                ('prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='پیش کد')),
                ('defaultDc', models.BooleanField(default=False, verbose_name='شرکت پخش پیش\u200cفرض')),
                ('defaultOc', models.BooleanField(default=False, verbose_name='شرکت سفارش\u200cدهنده پیش\u200cفرض')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
    ]
