# Generated by Django 4.2.1 on 2024-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyfaname',
        ),
        migrations.RemoveField(
            model_name='company',
            name='prefix',
        ),
        migrations.AlterField(
            model_name='company',
            name='defaultDc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='defaultOc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyFaName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
