# Generated by Django 4.2.1 on 2024-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_companyfaname_remove_company_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nationalid',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
