# Generated by Django 4.2.1 on 2024-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_nationalid_company_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NationalId',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
