# Generated by Django 4.2.1 on 2024-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
