# Generated by Django 4.2.1 on 2024-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_address_company_phone_company_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
