# Generated by Django 4.2.1 on 2024-04-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('UUID', models.CharField(max_length=20, unique=True)),
                ('UUIDCount', models.IntegerField(default=0)),
                ('RndEsalat', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('RndEsalatCount', models.IntegerField(default=0)),
                ('parent', models.CharField(max_length=20, null=True)),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
                ('levelid', models.SmallIntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.tblorder')),
            ],
        ),
    ]
