# Generated by Django 4.2.1 on 2024-05-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcode',
            table='Barcodes',
        ),
    ]
