# Generated by Django 4.2.1 on 2024-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_barcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='RndEsalat',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
