# Generated by Django 4.2.1 on 2024-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0003_barcode_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='orderid',
        ),
    ]
