# Generated by Django 4.2.1 on 2024-05-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0004_remove_barcode_orderid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcode',
            table=None,
        ),
    ]
