# Generated by Django 4.2.1 on 2024-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0005_alter_barcode_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='UUID',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='barcode',
            name='XmlStatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barcode',
            name='favoritecode',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='orderid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='orderserial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='whorderid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='barcode',
            table='BarCodes',
        ),
    ]
