# Generated by Django 4.2.1 on 2024-05-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0006_rename_uuid_barcode_uuid_barcode_xmlstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcode',
            table='Barcodes',
        ),
    ]
