# Generated by Django 4.2.1 on 2024-05-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0008_remove_barcode_favoritecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='order',
        ),
    ]
