# Generated by Django 4.2.1 on 2024-05-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0009_remove_barcode_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='orderid',
        ),
    ]
