# Generated by Django 4.2.1 on 2024-05-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orders_publishercode_orders_suppliercode'),
        ('barcode', '0010_remove_barcode_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orders'),
        ),
    ]
