# Generated by Django 4.2.1 on 2024-05-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0011_barcode_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='uuid',
            field=models.CharField(max_length=20),
        ),
    ]
