# Generated by Django 4.2.1 on 2024-05-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_xmlfile_ordertype'),
        ('barcode', '0012_alter_barcode_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturningBarcode',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('XmlStatus', models.SmallIntegerField(default=0)),
                ('uuid', models.CharField(max_length=20)),
                ('UUIDCount', models.IntegerField(blank=True, default=0, null=True)),
                ('RndEsalat', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('RndEsalatCount', models.IntegerField(default=0)),
                ('parent', models.CharField(max_length=20, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('levelid', models.SmallIntegerField(null=True)),
                ('whorderid', models.IntegerField(blank=True, null=True)),
                ('orderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
            ],
            options={
                'db_table': 'Returning_Barcodes',
            },
        ),
    ]
