# Generated by Django 4.2.1 on 2024-05-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_remove_warehouseorder_xml_file'),
        ('barcode', '0013_returningbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='WhOrderId',
            field=models.ForeignKey(db_column='WhOrderId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='order.warehouseorder'),
        ),
    ]
