# Generated by Django 4.2.1 on 2024-05-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0014_barcode_whorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='whorderid',
        ),
    ]
