# Generated by Django 4.2.1 on 2024-05-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_alter_orders_expdate_alter_orders_productcode'),
        ('barcode', '0015_remove_barcode_whorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='orderid',
            field=models.ForeignKey(db_column='OrderId', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orders'),
        ),
    ]
