# Generated by Django 4.2.1 on 2024-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0016_alter_barcode_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='favoriteCode',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
