# Generated by Django 4.2.1 on 2024-04-24 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.utils.file_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_addr', models.FileField(upload_to='XmlFiles/%Y/%m/%d/', verbose_name='انتخاب فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('file', models.FileField(upload_to=order.utils.file_utils.unique_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='dis', max_length=3, verbose_name=(('en', 'قابل استعلام'), ('dis', 'غیرقابل استعلام')))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xmlfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(verbose_name='شماره سفارش')),
                ('gtin', models.CharField(blank=True, max_length=14, null=True, verbose_name='کد GTIN')),
                ('batchnumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بچ')),
                ('expdate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ انقضا')),
                ('insertdate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ درج')),
                ('lastxmldate', models.CharField(blank=True, max_length=10, null=True, verbose_name='آخرین تاریخ XML')),
                ('deviceid', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دستگاه')),
                ('productionorderid', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سفارش تولید')),
                ('ordertype', models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع سفارش')),
                ('details', models.CharField(blank=True, max_length=100, null=True, verbose_name='جزئیات')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('distributercompanynid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_company', to='companies.company', verbose_name='کد ملی شرکت توزیع\u200cکننده')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'WarehouseOrders',
            },
        ),
        migrations.CreateModel(
            name='tblOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bn', models.CharField(max_length=14, verbose_name='شماره بچ')),
                ('md', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='تاریخ تولید')),
                ('ed', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='تاریخ انقضا')),
                ('sc', models.CharField(max_length=20, verbose_name='IRC')),
                ('lc', models.CharField(max_length=20, null=True, verbose_name='کد محلی')),
                ('no', models.PositiveIntegerField(verbose_name='تعداد')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('status', models.CharField(choices=[('en', 'قابل استعلام'), ('dis', 'غیرقابل استعلام')], default='dis', max_length=3, verbose_name='وضعیت')),
                ('GTIN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='GTIN محصول')),
            ],
        ),
    ]
