# Generated by Django 4.2.1 on 2024-04-20 12:46

from django.db import migrations, models
import order.utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblxmlorders',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblxmlorders',
            name='file',
            field=models.FileField(default='', upload_to=order.utils.file_utils.unique_file_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblxmlorders',
            name='original_file_name',
            field=models.CharField(default='', max_length=255, verbose_name='Original File Name'),
            preserve_default=False,
        ),
    ]
