# Generated by Django 4.2.1 on 2024-04-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='xml_file',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.xmlfile', verbose_name='فایل XML'),
            preserve_default=False,
        ),
    ]
