# Generated by Django 4.2.1 on 2024-04-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_tblxmlorders_error_message_tblxmlorders_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblxmlorders',
            old_name='User',
            new_name='user',
        ),
    ]
