# Generated by Django 4.2.1 on 2024-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_warehouseorder_xml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='no',
            field=models.CharField(default='', verbose_name='تعداد سفارش'),
            preserve_default=False,
        ),
    ]
