# Generated by Django 4.2.1 on 2024-04-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('order', '0003_warehouseorder_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='lc',
            field=models.CharField(blank=True, null=True, verbose_name='کد مجوز'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='ordercompanynid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_order', to='companies.company', verbose_name='کد ملی شرکت سفارش دهنده'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='px',
            field=models.CharField(default='', verbose_name='پیش\u200cشماره مجری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='wo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='distributercompanynid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_distributor', to='companies.company', verbose_name='کد ملی شرکت توزیع\u200cکننده'),
        ),
    ]
