# Generated by Django 4.2.1 on 2024-04-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_address_alter_company_name_and_more'),
        ('order', '0005_alter_tblxmlorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblxmlorders',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OD', to='companies.company'),
        ),
    ]
