# Generated by Django 4.2.1 on 2024-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_tblxmlorders_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfile',
            name='status',
            field=models.CharField(default='dis', max_length=3, verbose_name=(('en', 'قابل استعلام'), ('dis', 'غیرقابل استعلام'))),
        ),
    ]
