# Generated by Django 4.2.1 on 2024-04-24 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_warehouseorder_xml_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblorder',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblorder',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProductCode', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('BatchNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bn', to='order.tblorder', verbose_name='شماره بچ')),
                ('ExpDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ed', to='order.tblorder', verbose_name='تاریخ انقضا')),
                ('Numberinpack', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='order_no', to='order.warehouseorder', verbose_name='تعداد سفارش')),
                ('ProduceDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_md', to='order.tblorder', verbose_name='تاریخ تولید')),
                ('PublisherCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dc', to='order.warehouseorder', verbose_name='کد ملی شرکت عامل توزیع')),
                ('SupplierCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_oc', to='order.warehouseorder', verbose_name='کد ملی شرکت سفارش دهنده')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
