# Generated by Django 4.2.1 on 2024-04-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_xmlfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblxmlorders',
            name='document',
        ),
        migrations.AddField(
            model_name='tblxmlorders',
            name='xml_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.xmlfile'),
        ),
    ]
