# Generated by Django 4.2.1 on 2024-04-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_tblorder_createdat_tblorder_updatedat_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
