# Generated by Django 4.2.1 on 2024-04-21 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_tblxmlorders_document_tblxmlorders_xml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblorder',
            name='lc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tblorder',
            name='sc',
            field=models.CharField(default='', max_length=20, verbose_name='IRC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblorder',
            name='ed',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tblorder',
            name='md',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
