# Generated by Django 4.2.1 on 2024-04-30 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('levelId', models.IntegerField(unique=True, verbose_name='شناسه سطح')),
                ('level_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام سطح')),
                ('insert_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='WareHouseOrderLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_order', models.IntegerField(blank=True, null=True, verbose_name='تعداد سفارش')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.level', verbose_name='سطح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='order.warehouseorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'سطح سفارش انبار',
                'verbose_name_plural': 'سطوح سفارشات انبار',
                'db_table': 'warehouse_order_levels',
            },
        ),
    ]
