# Generated by Django 4.2.1 on 2024-04-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_level_warehouseorderlevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='orderid',
            field=models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.xmlfile', verbose_name='شماره سفارش'),
        ),
    ]
