# Generated by Django 4.2.1 on 2024-04-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_alter_warehouseorder_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='distributercompanynid',
            field=models.ForeignKey(db_column='distributercompanynid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_distributor', to='companies.company', verbose_name='کد ملی شرکت توزیع\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='userId',
            field=models.ForeignKey(db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
