# Generated by Django 4.2.1 on 2024-04-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_warehouseorder_distributercompanynid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='level',
            table='Levels',
        ),
    ]
