# Generated by Django 4.2.1 on 2024-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_level_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='no',
            field=models.CharField(blank=True, default='', null=True, verbose_name='تعداد سفارش'),
        ),
    ]
