# Generated by Django 4.2.1 on 2024-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_warehouseorder_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='px',
            field=models.CharField(blank=True, default='', null=True, verbose_name='پیش\u200cشماره مجری'),
        ),
    ]
