# Generated by Django 4.2.1 on 2024-05-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_id'),
        ('order', '0015_alter_warehouseorder_px'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='PublisherCode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='SupplierCode',
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='dc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_warehouse_distributor', to='companies.company', verbose_name='کد ملی شرکت توزیع\u200cکننده'),
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='no',
            field=models.CharField(blank=True, default='', null=True, verbose_name='تعداد سفارش'),
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_warehouse_order', to='companies.company', verbose_name='کد ملی شرکت سفارش دهنده'),
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='ot',
            field=models.CharField(choices=[('inc', 'incomming'), ('out', 'outgoing'), ('rtn', 'returning')], default='out', max_length=3),
            preserve_default=False,
        ),
    ]
