# Generated by Django 4.2.1 on 2024-05-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_warehouseorder_distributercompanynid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='ordertype',
            new_name='OrderType',
        ),
    ]
