# Generated by Django 4.2.1 on 2024-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_ordertype_warehouseorder_ordertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='OrderType',
            field=models.CharField(choices=[('inc', 'incomming'), ('out', 'outgoing'), ('rtn', 'returning')], max_length=3, null=True, verbose_name='ot'),
        ),
    ]
