# Generated by Django 4.2.1 on 2024-05-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_warehouseorder_ordertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='OrderId',
            field=models.ForeignKey(db_column='OrderId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.xmlfile'),
        ),
    ]
