# Generated by Django 4.2.1 on 2024-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_warehouseorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
