# Generated by Django 4.2.1 on 2024-05-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_warehouseorder_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='OrderCode',
        ),
        migrations.RenameField(
            model_name='xmlfile',
            old_name='OrderCode',
            new_name='PublisherCode',
        ),
    ]
