# Generated by Django 4.2.1 on 2024-05-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_rename_id_orders_ordercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='PublisherCode',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='oc'),
        ),
        migrations.AddField(
            model_name='orders',
            name='SupplierCode',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='oc'),
        ),
    ]
