# Generated by Django 4.2.1 on 2024-05-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orders_publishercode_orders_suppliercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='xml_file',
        ),
    ]
