# Generated by Django 4.2.1 on 2024-05-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        ('order', '0029_remove_warehouseorder_xml_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='batchnumber',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='expdate',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='lastxmldate',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='lc',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='no',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='ordercompanynid',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='productionorderid',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='px',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='wo',
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='DistributerCompanyNid',
            field=models.ForeignKey(db_column='DistributerCompanyNid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouseorder_dc', to='companies.company', verbose_name='dc'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='OrderType',
            field=models.CharField(choices=[('incomming', 'incomming'), ('outgoing', 'outgoing'), ('returning', 'returning')], max_length=10, null=True, verbose_name='ot'),
        ),
    ]
