# Generated by Django 4.2.1 on 2024-05-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_remove_warehouseorder_batchnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='PublisherCode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='SupplierCode',
        ),
    ]
