# Generated by Django 4.2.1 on 2024-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_orders_publishercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='NumberOfOrder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='orderid'),
        ),
    ]
