# Generated by Django 4.2.1 on 2024-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_xmlfile_numberoforder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlfile',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='xmlfile',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='xmlfile',
            name='OrderType',
            field=models.CharField(choices=[('inc', 'incomming'), ('out', 'outgoing'), ('rtn', 'returning')], max_length=3, null=True, verbose_name='ot'),
        ),
    ]
