# Generated by Django 4.2.1 on 2024-05-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_remove_xmlfile_createdat_remove_xmlfile_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='NumberOfOrder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='no'),
        ),
    ]
