# Generated by Django 4.2.1 on 2024-05-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_xmlfile_numberoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='OrderType',
            field=models.CharField(choices=[('incomming', 'incomming'), ('outgoing', 'outgoing'), ('returning', 'returning')], max_length=10, null=True, verbose_name='ot'),
        ),
    ]
