# Generated by Django 4.2.1 on 2024-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_xmlfile_ordertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmlfile',
            old_name='uploaded_at',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
