# Generated by Django 4.2.1 on 2024-05-02 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0036_rename_uploaded_at_xmlfile_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='PublisherCode',
            field=models.ForeignKey(db_column='publisher_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_warehouse_distributor', to='companies.company', verbose_name='dc'),
        ),
        migrations.AlterField(
            model_name='xmlfile',
            name='SupplierCode',
            field=models.ForeignKey(db_column='supplier_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xmlfile_oc', to='companies.company', verbose_name='oc'),
        ),
        migrations.AlterField(
            model_name='xmlfile',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='xmlfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
