# Generated by Django 4.2.1 on 2024-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_xmlfile_publishercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='LicenceCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='lc'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='NumberOfOrder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='od'),
        ),
    ]
