# Generated by Django 4.2.1 on 2024-05-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_orders_numberoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='NumberOfOrder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NO'),
        ),
    ]
