# Generated by Django 4.2.1 on 2024-05-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_xmlfile_numberoforder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='DistributerCompanyNid',
        ),
    ]
