# Generated by Django 4.2.1 on 2024-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_remove_warehouseorder_distributercompanynid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='OrderId',
        ),
        migrations.RemoveField(
            model_name='warehouseorder',
            name='userId',
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
