# Generated by Django 4.2.1 on 2024-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_remove_warehouseorder_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='OrderType',
            field=models.CharField(choices=[('incomming', 'incomming'), ('outgoing', 'outgoing'), ('returning', 'returning')], default='outgoing', max_length=10, verbose_name='ot'),
        ),
    ]
