# Generated by Django 4.2.1 on 2024-05-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        ('order', '0043_alter_xmlfile_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='DistributerCompanyNid',
            field=models.ForeignKey(db_column='DistributerCompanyNid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouseorder_dc', to='companies.company', verbose_name='dc'),
        ),
    ]
