# Generated by Django 4.2.1 on 2024-05-08 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0044_warehouseorder_distributercompanynid'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='batchnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='expdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='کد GTIN'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='lastxmldate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='lc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='no',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='ordercompanynid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_order', to='companies.company'),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='productionorderid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='px',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='userId',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='wo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
