# Generated by Django 4.2.1 on 2024-05-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_warehouseorder_batchnumber_warehouseorder_expdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='id',
            field=models.IntegerField(editable=False, unique=True),
        ),

        migrations.AddField(
            model_name='warehouseorder',
            name='order_id',
            field=models.OneToOneField(db_column='OrderId', default=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.xmlfile'),
            preserve_default=False,
        ),
    ]
