# Generated by Django 4.2.1 on 2024-05-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_alter_warehouseorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='xml_file',
            field=models.ForeignKey(db_column='xml_file', default=5, on_delete=django.db.models.deletion.CASCADE, to='order.xmlfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='order_id',
            field=models.AutoField(db_column='OrderId', primary_key=True, serialize=False),
        ),
    ]
