# Generated by Django 4.2.1 on 2024-05-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_warehouseorder_xml_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='xml_file',
            field=models.ForeignKey(blank=True, db_column='xml_file', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.xmlfile'),
        ),
    ]
