# Generated by Django 4.2.1 on 2024-05-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_alter_warehouseorder_xml_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xmlfile',
            table='XMLFiles',
        ),
    ]
