# Generated by Django 4.2.1 on 2024-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_xmlfile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='xml_file',
        ),
    ]
