# Generated by Django 4.2.1 on 2024-05-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        ('order', '0051_remove_warehouseorder_xml_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='ordercompanynid',
            field=models.ForeignKey(blank=True, db_column='ordercompanynid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_order', to='companies.company'),
        ),
    ]
