# Generated by Django 4.2.1 on 2024-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_alter_warehouseorder_ordercompanynid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='id',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='order_id',
            field=models.PositiveIntegerField(db_column='OrderId', primary_key=True, serialize=False),
        ),
    ]
