# Generated by Django 4.2.1 on 2024-05-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        ('order', '0054_remove_warehouseorder_insertdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='lastxmldate',
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='DistributerCompanyNid',
            field=models.ForeignKey(db_column='DistributerCompanyNid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DC', to='companies.company', verbose_name='dc'),
        ),
        migrations.AlterField(
            model_name='warehouseorder',
            name='ordercompanynid',
            field=models.ForeignKey(blank=True, db_column='ordercompanynid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_order', to='companies.company', verbose_name='OC'),
        ),
    ]
