# Generated by Django 4.2.1 on 2024-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_warehouseorder_insertdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='lastxmldate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
