# Generated by Django 4.2.1 on 2024-05-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_warehouseorder_lastxmldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='order_id',
            new_name='OrderId',
        ),
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='OrderType',
            new_name='ordertype',
        ),
    ]
