# Generated by Django 4.2.1 on 2024-05-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_rename_order_id_warehouseorder_orderid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='deviceid',
            new_name='DeviceId',
        ),
    ]
