# Generated by Django 4.2.1 on 2024-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_rename_deviceid_warehouseorder_deviceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='ordertype',
            new_name='orderType',
        ),
    ]
