# Generated by Django 4.2.1 on 2024-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_rename_ordertype_warehouseorder_ordertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='orderType',
            field=models.CharField(choices=[('incomming', 'incomming'), ('outgoing', 'outgoing'), ('returning', 'returning')], max_length=10, verbose_name='ot'),
        ),
    ]
