# Generated by Django 4.2.1 on 2024-05-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_alter_warehouseorder_ordertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseorder',
            old_name='orderType',
            new_name='ordertype',
        ),
    ]
