# Generated by Django 4.2.1 on 2024-05-12 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_rename_ordertype_warehouseorder_ordertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ExpDate',
            field=models.CharField(db_column='ProductCode', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ed'),
        ),
    ]
