# Generated by Django 4.2.1 on 2024-05-12 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_producercompanycode'),
        ('order', '0064_alter_orders_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ExpDate',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ed'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ProductCode',
            field=models.ForeignKey(db_column='ProductCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='gtin'),
        ),
    ]
