# Generated by Django 4.2.1 on 2024-04-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('gtin', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='کد جهانی تجاری (GTIN)')),
                ('productfrname', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام فارسی محصول')),
                ('irc', models.CharField(blank=True, max_length=16, null=True, verbose_name='پروانه بهداشتی (IRC)')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('producercompanycode', models.ForeignKey(db_column='ProducerCompanyCode', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='شرکت تولید کننده')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
