# Generated by Django 4.2.1 on 2024-04-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producercompanycode',
            field=models.ForeignKey(db_column='producercompanycode', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='شرکت تولید کننده'),
        ),
    ]
