# Generated by Django 4.2.1 on 2024-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_producercompanycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
