# Generated by Django 4.2.1 on 2024-05-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_id'),
        ('products', '0003_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producercompanycode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productfrname',
        ),
        migrations.AlterField(
            model_name='product',
            name='irc',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='GTIN',
            field=models.CharField(default='', max_length=14, primary_key=True, serialize=False, verbose_name='gtin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProducerCompanyCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_oc', to='companies.company', verbose_name='oc'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductFrName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
