# Generated by Django 4.2.1 on 2024-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_gtin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GTIN',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='gtin'),
        ),
    ]
