# Generated by Django 4.2.1 on 2024-04-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_address_alter_company_name_and_more'),
        ('products', '0004_alter_product_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='OC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='شرکت تولید کننده'),
        ),
    ]
