# Generated by Django 4.2.1 on 2024-05-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_nationalid'),
        ('products', '0007_alter_product_producercompanycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProducerCompanyCode',
            field=models.ForeignKey(db_column='ProducerCompanyCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='companies.company', verbose_name='oc'),
        ),
    ]
